### ISSUE TITLE
Serilog.LogEventConverter: NullReferenceException when formatting exception stack trace.

### ISSUE THREAD

**Issue by pcooper** [elastic/ecs-dotnet#111]
Serilog stack trace formatting for exceptions  in `LogEventConverter.cs` can cause a NullReferenceException when attempting to access a null stack trace frame of an inner exception.  This causes message formatting and sinking to fail entirely [here](https://github.com/elastic/ecs-dotnet/blob/1.5.1/src/Elastic.CommonSchema.Serilog/LogEventConverter.cs#L352).

**ECS .NET assembly version (e.g. 1.4.2)**:1.5.1
**.NET framework / OS**: net472, win10, but applies to any compatible Fx or OS version.

**Description of the problem, including expected versus actual behavior**:
A NullReferenceExeption is internally thrown and swallowed, but is accessible through Serilog's `SelfLog` debugging tool.  Expected: the log event to be formatted with exception and stack trace.
Actual: nothing was logged.  Serilog debugger captures the null ref.

**Steps to reproduce**:
 1. Run this code in a simple console app.  Uses Serilog console sink.
```cs
class Program
    {
        static void Main(string[] args)
        {
            Serilog.Debugging.SelfLog.Enable(msg => Console.WriteLine(msg));

            var logger = new LoggerConfiguration()
                .WriteTo.Console(new EcsTextFormatter())
                .CreateLogger();

            try
            {
                throw new Exception("Error", new Exception());  // This 'inner exception' has no stack frame.
            }
            catch (Exception ex)
            {
                logger.Error(ex, "An error occurred.");
            }

            Console.ReadLine();
        }
    }
```

Output:
```
2020-11-04T17:09:55.0003908Z Caught exception while emitting to sink Serilog.Sinks.SystemConsole.ConsoleSink: System.NullReferenceException: Object reference not set to an instance of an object.
   at Elastic.CommonSchema.Serilog.LogEventConverter.CatchErrors(IReadOnlyCollection`1 errors)
   at Elastic.CommonSchema.Serilog.LogEventConverter.GetError(IReadOnlyList`1 exceptions)
   at Elastic.CommonSchema.Serilog.LogEventConverter.ConvertToEcs(LogEvent logEvent, IEcsTextFormatterConfiguration configuration)
   at Elastic.CommonSchema.Serilog.EcsTextFormatter.Format(LogEvent logEvent, TextWriter output)
   at Serilog.Sinks.SystemConsole.ConsoleSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
```

Admittedly it doesn't make sense why an inner exception would be initialized in this manner, but I don't think ECS.Serilog should fail to format an ECS message because of it.  I discovered this issue due to capturing and logging an error from a 3rd party NuGet package.

Proposal: better null handling in stack trace formatting.

**Comment by pcooper** [comment]
Apologies, this is a duplicate of #102.  Tracking there instead.
