### ISSUE TITLE
NullReferenceException when Serilog.Events.LogEvent has property value == Null

### ISSUE THREAD

**Issue by MikhailIzvekov** [elastic/ecs-dotnet#29]
Call Stack:
```
   at System.Object.GetType()
   at Elastic.CommonSchema.Serialization.MetaDataDictionaryConverter.Write(Utf8JsonWriter writer, IDictionary`2 value, JsonSerializerOptions options)
   at Elastic.CommonSchema.Serialization.BaseJsonConverter.Write(Utf8JsonWriter writer, Base value, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnWrite(WriteStackFrame& current, Utf8JsonWriter writer)
   at System.Text.Json.JsonPropertyInfo.Write(WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, Object value, Type type, JsonSerializerOptions options)
   at Elastic.CommonSchema.Base.Serialize(Stream s)
   at Serilog.Sinks.File.FileSink.Emit(LogEvent logEvent)
   at Serilog.Sinks.RollingFile.RollingFileSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
```

LogEvent:
![image](https://user-images.githubusercontent.com/26023871/72254281-f673f480-361c-11ea-8f20-b534cae62be7.png)

Output:
```
...
	"_metadata": {
		"protocol": "HTTP/1.1",
		"method": "GET",
		"content_type": 
```

**Comment by codebrain** [comment]
Hi @MikhailIzvekov, thanks for opening.  Can I please ask which version of the assembly are you using? `1.4.0-beta1`?

**Comment by MikhailIzvekov** [comment]
Yes.
