### ISSUE TITLE
[BUG] Cannot write log via Elastic.Serilog.Sinks

### ISSUE THREAD

**Issue by AndriiDzendzia** [elastic/ecs-dotnet#463]
**ECS integration/library project(s) (e.g. Elastic.CommonSchema.Serilog)**: Elastic.Serilog.Sinks 8.12.2

**ECS schema version (e.g. 1.4.0)**: 8.12.2

**ECS .NET assembly version (e.g. 1.4.2)**: 

**Elasticsearch version (if applicable)**: 8.16.0

**.NET framework / OS**: 8

**Description of the problem, including expected versus actual behavior**:

Observed an exception while writing to [data stream]

**Steps to reproduce**:

SelfLog.Enable(Console.Error);
services.AddSerilog((services, lc) => lc
    .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(services.GetService<ElasticsearchClient>()!.Transport)
    {
        BootstrapMethod = BootstrapMethod.Failure,
        IlmPolicy = "logs-dotnet",
        DataStream = new DataStreamName("logs", "dotnet", "quartz")
    })
    .Enrich.FromLogContext()
    .MinimumLevel.Information());

Then in console, you will get the following:
```
2024-11-21T19:54:51.3495000Z Observed an exception while writing to [data stream]
2024-11-21T19:54:51.3496397Z System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<!!0> Elastic.Transport.TransportExtensions.RequestAsync(Elastic.Transport.ITransport, Elastic.Transport.HttpMethod, System.String, Elastic.Transport.PostData, Elastic.Transport.RequestParameters, System.Threading.CancellationToken)'.
   at Elastic.Ingest.Elasticsearch.ElasticsearchChannelBase`2.ExportAsync(ITransport transport, ArraySegment`1 page, CancellationToken ctx)
   at Elastic.Ingest.Transport.TransportChannelBase`4.ExportAsync(ArraySegment`1 buffer, CancellationToken ctx)
   at Elastic.Channels.BufferedChannelBase`3.ExportBufferAsync(ArraySegment`1 items, IOutboundBuffer`1 buffer)
```

**Comment by stevejgordon** [comment]
@AndriiDzendzia, I suspect this may be due to changes we've made in Transport, which we have yet to pull into this library. Do you reference Elastic.Transport directly or via Elastic.Clients.Elasticsearch? If so, can you confirm which versions of those packages you have referenced?

**Comment by AndriiDzendzia** [comment]
> [@AndriiDzendzia](https://github.com/AndriiDzendzia), I suspect this may be due to changes we've made in Transport, which we have yet to pull into this library. Do you reference Elastic.Transport directly or via Elastic.Clients.Elasticsearch? If so, can you confirm which versions of those packages you have referenced?

Firstly, it was Elastic.Transport 0.5.2 via Elastic.Clients.Elasticsearch 8.16.0. Then, I updated it to 8.16.1 and 0.5.5, and both are installed directly.

**Comment by stevejgordon** [comment]
Ah, okay, thanks for confirming. We'll need to publish an update to this library, taking a dependency on 0.5.5. Until then, can you stick with 8.16.0.

**Comment by stevejgordon** [comment]
@AndriiDzendzia Hopefully, 8.12.3 should fix this issue.

**Comment by AndriiDzendzia** [comment]
@stevejgordon Yeah, it works. Great thanks)
